---

- name: Server initialization
  hosts: kube-0
  become: yes

  tasks:
    - name: Add firewall and configure 80/443
      include_tasks: tasks/ufw.yaml

  handlers:
    - include_tasks: handlers.yaml

- name: Build a single node k3s cluster
  hosts: kube-0
  vars:
    k3s_become: true
  roles:
    - role: xanmanning.k3s
